### ISSUE TITLE
Some packages could not be installed

### ISSUE THREAD

**Issue by pixelr0** [ubports/unity8-desktop-install-tools#1]
fresh 16.04 install

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity8-desktop-session : Depends: unity8 but it is not going to be installed
                          Recommends: qtubuntu-print but it is not going to be installed
                          Recommends: webbrowser-app
E: Unable to correct problems, you have held broken packages.

---------------------------------------------------------------

and then this issue

Reading state information... Done
162 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: http://repo.ubports.com/dists/xenial/Release.gpg: Signature by key B551C909D750AA744948E9ED4BD4B4D6DBB583F1 uses weak digest algorithm (SHA1)
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repo.ubports.com_dists_xenial_Release
W: http://repo.ubports.com/dists/xenial_-_mir26/Release.gpg: Signature by key B551C909D750AA744948E9ED4BD4B4D6DBB583F1 uses weak digest algorithm (SHA1)
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repo.ubports.com_dists_xenial%5f-%5fmir26_Release
Reading package lists... Done

**Comment by mariogrip** [comment]
Got the "weak digest algorithm" an invalid "date" fixed now, will get a fresh 16.04 install up and running and look into the dependency problem.

**Comment by mariogrip** [comment]
Just tested a clean ubuntu server, that seems to work. will try to install "ubuntu-desktop" and then install unity8 and see what happens

**Comment by mariogrip** [comment]
Humm, still seems to install just fine, could you try it again? if that does not work, try running `sudo apt install unity8` and copy the output

**Comment by pixelr0** [comment]
sudo apt install unity8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity8 : Depends: qml-module-ubuntu-web but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by mariogrip** [comment]
could you try `sudo apt install qml-module-ubuntu-web`

**Comment by pixelr0** [comment]
i think it's already installed

apt list qml-module-ubuntu-web -a
Listing... Done
qml-module-ubuntu-web/xenial_-_mir26 0.24+ubports+0~20171228063000.4~1.gbp9be809 amd64 [upgradable from: 0.23+16.04.20161028-0ubuntu2]
qml-module-ubuntu-web/xenial 0.23+16.04.20170321-0ubuntu1 amd64
qml-module-ubuntu-web/xenial-updates,now 0.23+16.04.20161028-0ubuntu2 amd64 [installed,upgradable to: 0.24+ubports+0~20171228063000.4~1.gbp9be809]
qml-module-ubuntu-web/xenial 0.23+16.04.20160413-0ubuntu1 amd64

-------------------------------------------------------------------

sudo apt install qml-module-ubuntu-web
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qml-module-ubuntu-web : Depends: liboxideqt-qmlplugin (>= 1.15.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by pixelr0** [comment]
and i have 81 packages kept back, that i can't upgrade

The following packages have been kept back:
  indicator-datetime indicator-printers libaccounts-qt5-1 libgsettings-qt1 liboxideqt-qmlplugin liboxideqtcore0 liboxideqtquick0 libqt4-dbus
  libqt4-declarative libqt4-network libqt4-script libqt4-sql libqt4-sql-sqlite libqt4-xml libqt4-xmlpatterns libqt5clucene5
  libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5designercomponents5 libqt5feedback5 libqt5gui5 libqt5help5
  libqt5multimedia5 libqt5network5 libqt5opengl5 libqt5organizer5 libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5quick5
  libqt5quicktest5 libqt5quickwidgets5 libqt5script5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webkit5 libqt5widgets5
  libqt5xml5 libqt5xmlpatterns5 libqtcore4 libqtdbus4 libqtgui4 libsignon-extension1 libsignon-plugins-common1 libsignon-qt5-1
  libubuntugestures5 libubuntutoolkit5 oxideqt-codecs-extra qdbus qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
  qml-module-qtfeedback qml-module-qtgraphicaleffects qml-module-qtquick-controls qml-module-qtquick-layouts qml-module-qtquick-window2
  qml-module-qtquick2 qml-module-qttest qml-module-ubuntu-components qml-module-ubuntu-layouts qml-module-ubuntu-performancemetrics
  qml-module-ubuntu-test qml-module-ubuntu-web qmlscene qt5-qmake qtbase5-dev-tools qtchooser qtcreator-data qtdeclarative5-dev-tools
  qttools5-dev-tools qtxmlpatterns5-dev-tools signon-plugin-password signon-ui-x11 signond ubuntu-ui-toolkit-theme webapp-container
  webbrowser-app
0 upgraded, 0 newly installed, 0 to remove and 81 not upgraded.

**Comment by mariogrip** [comment]
try doing `sudo apt dist-upgrade`

**Comment by pixelr0** [comment]
upgrading 

The following packages will be REMOVED:
  appmenu-qt5 qtcreator
The following NEW packages will be installed:
  geoclue-2.0 iio-sensor-proxy libclick-0.4-0 libcontent-hub0 libertined libgeoclue-2-0 liblibertine1 liblttng-ust-ctl2 liblttng-ust0
  libqt5systeminfo5 libubuntu-app-launch3 libubuntumetrics5 liburcu4 libxcb-xinerama0 python3-distro-info python3-libertine python3-psutil
  qml-module-qtqml-models2 qml-module-qtsysteminfo qml-module-ubuntu-components-labs qt5-gtk-platformtheme qtdeclarative5-ubuntu-content1
  qtdeclarative5-ubuntu-ui-extras0.2
The following packages will be upgraded:
  indicator-datetime indicator-printers libaccounts-qt5-1 libgsettings-qt1 liboxideqt-qmlplugin liboxideqtcore0 liboxideqtquick0 libqt4-dbus
  libqt4-declarative libqt4-network libqt4-script libqt4-sql libqt4-sql-sqlite libqt4-xml libqt4-xmlpatterns libqt5clucene5
  libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5designercomponents5 libqt5feedback5 libqt5gui5 libqt5help5
  libqt5multimedia5 libqt5network5 libqt5opengl5 libqt5organizer5 libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5quick5
  libqt5quicktest5 libqt5quickwidgets5 libqt5script5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webkit5 libqt5widgets5
  libqt5xml5 libqt5xmlpatterns5 libqtcore4 libqtdbus4 libqtgui4 libsignon-extension1 libsignon-plugins-common1 libsignon-qt5-1
  libubuntugestures5 libubuntutoolkit5 oxideqt-codecs-extra qdbus qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
  qml-module-qtfeedback qml-module-qtgraphicaleffects qml-module-qtquick-controls qml-module-qtquick-layouts qml-module-qtquick-window2
  qml-module-qtquick2 qml-module-qttest qml-module-ubuntu-components qml-module-ubuntu-layouts qml-module-ubuntu-performancemetrics
  qml-module-ubuntu-test qml-module-ubuntu-web qmlscene qt5-qmake qtbase5-dev-tools qtchooser qtcreator-data qtdeclarative5-dev-tools
  qttools5-dev-tools qtxmlpatterns5-dev-tools signon-plugin-password signon-ui-x11 signond ubuntu-ui-toolkit-theme webapp-container
  webbrowser-app
81 upgraded, 23 newly installed, 2 to remove and 0 not upgraded.

**Comment by pixelr0** [comment]
so, the image is fresh, but i have some additional packages installed like qtcreator, chrome, telegram

**Comment by mariogrip** [comment]
ah! seems like qtcreator was the problem, we need to rebuild that to use the newer qt version

**Comment by pixelr0** [comment]
probably :D / yay i haz unity8! thanks
![screenshot20171229_204100046](https://user-images.githubusercontent.com/333589/34444728-e28a4b16-ecd8-11e7-83c2-b9d89aa66211.png)
