### ISSUE TITLE
Unity8 session broken on bionic by latest mir updates

### ISSUE THREAD

**Issue by WebDrake** [ubports/unity8-desktop-install-tools#18]
The latest updates to bionic include an upgrade to mir 0.30.0.1.  This seems to break the ubports Unity8 desktop session: after typing the password to log in, nothing further happens (I seem to be stuck on lightdm).

Things obviously aren't 100% broken, since if I hit the power-off button on my laptop, the shutdown overlay appears (allowing me to choose between suspend, restart, and power-off), the Unity8 desktop fails to launch.

**Comment by WebDrake** [comment]
Might be a more general upstream issue: https://bugs.launchpad.net/ubuntu/+source/libglvnd/+bug/1751414  I'll keep an eye on things there.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/unity8#30
