### ISSUE TITLE
Cannot install Unity8 on Ubuntu 18.04 daily build (2018.03.09)

### ISSUE THREAD

**Issue by ghost** [ubports/unity8-desktop-install-tools#19]
> If you get an option to select display manager, please select lightdm!
> 
> Press enter to continue
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  unity8-desktop-session : Depends: qtmir-desktop but it is not going to be installed
>                           Depends: qtubuntu-appmenutheme
>                           Depends: qtubuntu-desktop but it is not going to be installed
>                           Depends: unity8 but it is not going to be installed
>                           Depends: url-dispatcher but it is not going to be installed
>                           Recommends: indicator-transfer but it is not installable
>                           Recommends: qtubuntu-print but it is not installable
>                           Recommends: ubuntu-terminal-app but it is not going to be installed
>                           Recommends: unity-scope-mediascanner2 but it is not installable
>                           Recommends: webbrowser-app but it is not installable
> E: Unable to correct problems, you have held broken packages.

**Comment by ghost** [comment]
tried installing on a fresh install. same problem

**Comment by littlephone** [comment]
Same issue here. For me, I have got the unmet dependencies:
 unity8-desktop-session : Depends: unity8 but it is not going to be installed
                          Recommends: indicator-transfer but it is not installable
                          Recommends: qtubuntu-print but it is not installable
                          Recommends: ubuntu-terminal-app but it is not going to be installed
                          Recommends: unity-scope-mediascanner2 but it is not installable
                          Recommends: webbrowser-app but it is not installable

**Comment by littlephone** [comment]
I found something wrong about the packages. The qt-base-abi and qt-declarative-abi package is missing from the repository. (Maybe it's being moved or updated). When I attempted to install unity8, apt tells me that they're not installable

**Comment by AlanGriffiths** [comment]
This issue arose at the time Qt was upgraded from 5.9.3 to 5.9.4 in the Ubuntu 18.04 repository. I imagine that the UBport build has dependencies on 5.9.3 and that causes these conflicts.

Just needs a "rebuild the world"?

**Comment by mariogrip** [comment]
Fixed
