### ISSUE TITLE
qtbase-abi-5-9-2 is not installable

### ISSUE THREAD

**Issue by littlephone** [ubports/unity8-desktop-install-tools#20]
**What's tested**

When I try to use the script install.sh to install unity8, it said that qtbase-abi-5-9-2 is not installable. Then I attempt to open the repo site http://repos.ubports.com and find out that multiple apps are depending on such package.

Then I typed in the command:
`apt-cache search qtbase-abi` 
the result is:
`libqt5core5a - Qt 5 core module`

I think the dependency has changed and now the unity8 should be depending on libqt5core5a instead of qtbase-abi and qtdeclarative-abi for libqt5qml5. 

This issues happens in **either** bionic or xenial as far as I have concerned. 

**Reference**
#17 
#19 

**What's not tested**
Running unity8

**Comment by mariogrip** [comment]
Fixed
