### ISSUE TITLE
Unity8 thinks it runs on a phone

### ISSUE THREAD

**Issue by vanyasem** [ubports/unity8-desktop-install-tools#26]
I installed Unity8 on Ubuntu 18.04. I was able to launch it applying the workaround in #22.

I guess Unity8 toggled a phone mode, as all apps are fullscreen and  the dash is similar to what i see on my phone. There is no "Desktop" toggle anywhere (i checked the pulldown menu and the settings apps)

I tried increasing the resolution greatly and rebooting, but that didn't help.

![2018-05-23-152920_1812x1543_scrot](https://user-images.githubusercontent.com/13350458/40424796-38d50e10-5e9f-11e8-9e72-257c40c18719.png)
![2018-05-23-153250_3840x2060_scrot](https://user-images.githubusercontent.com/13350458/40424847-575850fe-5e9f-11e8-8877-8b375ddd9659.png)

**Comment by Flohack74** [comment]
But you must admit it looks great :)

**Comment by vanyasem** [comment]
https://t.me/UBports_Unity8/1871

Chow Raynold said that this is related to the fact that i am running it from the shell as an app, and not via a display manager. Closing the issue
