### ISSUE TITLE
Unity8 starts with Mir 0.32.0 from the UBports repo, but not with Mir from the mir-team ppa

### ISSUE THREAD

**Issue by GizmoChicken** [ubports/unity8-desktop-install-tools#35]
Although I can currently log into Unity8 using the version of Mir 0.32.0 installed from the UBports repo (which version is installed using the [Unity8 install script](https://github.com/ubports/unity8-desktop-install-tools)), I am unable to log into Unity8 using a version of Mir 0.32.0 installed from [ppa:mir-team/release](https://launchpad.net/~mir-team/+archive/ubuntu/release) or using a version of Mir 0.32.1 installed from [ppa:mir-team/rc](https://launchpad.net/%7Emir-team/+archive/ubuntu/rc).

For more details, please see https://github.com/MirServer/mir/pull/456

**Comment by AlanGriffiths** [comment]
On closer [inspection](https://github.com/ubports/mir/commit/326dd988f67f06b76331a2bd4bed645ceda4d928), UBports is not tracking Mir releases, it is pulling code from master.

In this case, that picked up a bad version of DefaultServerConfiguration::the_console_services() that incorrectly tries to use logind when a VT is specified. That breaks badly on 16.04 and is inefficient almost everywhere, but explains why the UBports version of Mir appears to work.

**Comment by AlanGriffiths** [comment]
This seems to be working now

**Comment by GizmoChicken** [comment]
The good:  I can confirm that, after first installing Unity8 from the UBports repo, and then installing Mir 0.32.1 from [ppa:mir-team/release](https://launchpad.net/~mir-team/+archive/ubuntu/release), I can now log into Unity8 using LightDM.

The bad:  Although perhaps stemming from a different bug, I note that, upon logging out of Unity8, I am unable log into Unty7 using LightDM.  Rather, when attempting to do so, I remain stuck at the LightDM login screen until I reboot.  Upon reboot, I can log into Unity7, then out of Unity7, and then back into Unity7.   But if I log into Unity8, I need to reboot if I want to log into Unity7.

Not sure if the "the bad" should be submitted as a new bug report, or should be further discussed here.  As an aside, at this point, I don't really have much need for switching between Unity8 and other DEs.  So from my perspective, fixing "the bad" described above isn't urgent.  But if exploring this helps sort out undiscovered issues with Mir, I'm happy to help provide logs and/or other information.

EDIT:  I just now noticed that, upon logging out of Unity8, I am _able_ to log into GNOME using LightDM.  And in fact, I can switch between Unity8 and GNOME without trouble using LightDM.  Also, I can switch between GNOME and Unity7 without trouble using LightDM.  But upon logging out of Unity8, I still can't log into Unity7 using LightDM.   Very strange.

**Comment by AlanGriffiths** [comment]
> @GizmoChicken Not sure if the "the bad" should be submitted as a new bug report, or should be further discussed here. As an aside, at this point, I don't really have much need for switching between Unity8 and other DEs. So from my perspective, fixing "the bad" described above isn't urgent. But if exploring this helps sort out undiscovered issues with Mir, I'm happy to help provide logs and/or other information.

It's a different problem, log it separately so this one can be closed. (Which makes progress visible)

**Comment by GizmoChicken** [comment]
Will do.  Thanks.
