### ISSUE TITLE
enable-mir0-29.sh not sure it worked

### ISSUE THREAD

**Issue by pixelr0** [ubports/unity8-desktop-install-tools#4]
so, after running the script i have the following warnings

All packages are up to date.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/ubports.list:2 and /etc/apt/sources.list.d/ubports.list:3

and it looks like the installed mir is still 0.26.4
libmirserver43/xenial_-_mir26,now 0.26.4+ubports1+0~20171228024232.1~1.gbp21d10f amd64 [installed,automatic]
libmirplatform15/xenial_-_mir26,now 0.26.4+ubports1+0~20171228024232.1~1.gbp21d10f amd64 [installed,automatic]

**Comment by pixelr0** [comment]
line 16 in https://github.com/ubports/unity8-desktop-install-tools/blob/master/enable-mir0-29.sh

shoud maybe be ""deb http://repo.ubports.com/ xenial_-_mir29 main" » /etc/apt/sources.list.d/ubports.list"?

**Comment by mariogrip** [comment]
Yeah that's correct, i added the wrong one. Updated it now and made it so there will be no duplicates.

**Comment by pixelr0** [comment]
yay! mir 0.29
libmirserver46/xenial_-_mir29,now 0.29.0+0~20171230070950.2~1.gbp65dfcf amd64 [installed,automatic]

thanks! :D

**Comment by mariogrip** [comment]
:)
