### ISSUE TITLE
can't login into unity8 mir0.1.0 / sddm 

### ISSUE THREAD

**Issue by pixelr0** [ubports/unity8-desktop-install-tools#40]
just bounces back to the login screen sddm 

where can i see the logs?

**Comment by pixelr0** [comment]
/var/log/syslog

Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03:09:53:40.030] qtmir.screens: ScreensModel::ScreensModel
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03:09:53:40.032] QSocketNotifier: Can only be used with threads started with QThread
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036349] mirserver: Starting
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036418] <DEBUG> mirserver: Not trying logind: "DISPLAY" is set and X need not have claimed the VT
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036464] <DEBUG> mirserver: Not using Linux VT subsystem for session management: Failed to find the current VT
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036477] <DEBUG> mirserver: No session management supported
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036487] VT switch key handler: No VT switching support available: NullConsoleServices does not support VT switching
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036565] mircommon: Loading modules from: /usr/lib/x86_64-linux-gnu/mir/server-platform
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036594] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/server-mesa-x11.so.15
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036609] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-mesa-kms.so.15
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.036618] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/server-mesa-x11.so.13
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.037218] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-mesa-kms.so.13
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.037515] <WARNING> mircommon: Failed to load module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-mesa-kms.so.13 (error was:/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-mesa-kms.so.13: symbol _ZNK3mir4udev7Monitor14process_eventsERKSt8functionIFvNS1_9EventTypeERKNS0_6DeviceEEE version MIRPLATFORM_0.27 not defined in file libmirplatform.so.16 with link time reference)
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.037547] mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.7
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: Invalid MIT-MAGIC-COOKIE-1 key[2018-10-03 09:53:40.038636] mirplatform: Found graphics driver: mir:mesa-x11 (version 1.0.0)
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.039589] mesa-kms: Attempt to acquire device from NullConsoleServices.
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03 09:53:40.039696] mirplatform: Found graphics driver: mir:mesa-kms (version 1.0.0)
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: Invalid MIT-MAGIC-COOKIE-1 key[2018-10-03 09:53:40.039886] mirplatform: Found graphics driver: mir:mesa-x11 (version 0.31.2)
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: [2018-10-03:09:53:40.040] Exception while creating graphics platform
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: ERROR: /build/varlibjenkinsworkspaceubportsmirbionicUNQPKFJLHMPQNTZUKEIEMUTNXGDFGGGSWMKSQVHPZZQmirgbpdedebdsc/src/platform/graphics/platform_probe.cpp(108): Throw in function std::shared_ptr<mir::SharedLibrary> mir::graphics::module_for_device(const std::vector<std::shared_ptr<mir::SharedLibrary> >&, const mir::options::ProgramOption&, const std::shared_ptr<mir::ConsoleServices>&)
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: std::exception::what: Failed to find platform for current system
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: /usr/bin/unity8-session: line 75: [: !=: unary operator expected
Oct  3 09:53:40 pixel-desktop unity8-session[4255]: /usr/bin/unity8-session: line 79: kill: (4322) - No such process
Oct  3 09:53:40 pixel-desktop systemd[1967]: Started Unity Shell v8.
Oct  3 09:53:40 pixel-desktop systemd[1967]: Reached target Target representing the lifecycle of the indicators. Each indicator should be bound to it in its individual service file..
Oct  3 09:53:40 pixel-desktop sddm-helper[4091]: [PAM] Closing session
Oct  3 09:53:40 pixel-desktop sddm-helper[4091]: [PAM] Ended.
Oct  3 09:53:40 pixel-desktop sddm[1752]: Auth: sddm-helper exited successfully
Oct  3 09:53:40 pixel-desktop sddm[1752]: Greeter stopping...
Oct  3 09:53:40 pixel-desktop sddm[1752]: Socket server stopping...
Oct  3 09:53:40 pixel-desktop sddm[1752]: Socket server stopped.
Oct  3 09:53:40 pixel-desktop sddm[1752]: Display server stopping...

**Comment by mariogrip** [comment]
Could you do `dpkg -l | grep mir`?

**Comment by pixelr0** [comment]
$ dpkg -l | grep mir
ii  libertine-xmir-tools                            1.7.2+ubports+0~20180214124619.3~1.gbp4ae89b            amd64        helper apps for using and interacting with Xmir
ii  libmiral2:amd64                                 1.5.0.0.31.0.1+0ubports2+0~20180310134906.6~1.gbpa17c3e amd64        Display server for Ubuntu - ABI preserving abstraction layer
ii  libmiral3:amd64                                 2.4.0.1.0.0+0~20181002215523.10~1.gbpdede9b             amd64        Display server for Ubuntu - ABI preserving abstraction layer
ii  libmirclient-dev:amd64                          1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - development headers
ii  libmirclient9:amd64                             1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - client library
ii  libmircommon-dev:amd64                          1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - development headers
ii  libmircommon7:amd64                             1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - shared library
ii  libmircookie-dev:amd64                          1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Produce and verify spoof-resistant timestamps - development headers
ii  libmircookie2:amd64                             1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Produce and verify spoof-resistant timestamps - runtime library
ii  libmircore-dev:amd64                            1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - development headers
ii  libmircore1:amd64                               1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - shared library
ii  libmirplatform16:amd64                          1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - platform library
ii  libmirprotobuf3:amd64                           1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - RPC definitions
ii  libmirserver45:amd64                            0.28.1+18.04.20171030-ubuntu0~1309~ubuntu17.10.1        amd64        Display server for Ubuntu - server library
ii  libmirserver46:amd64                            0.30.0-0ubuntu17.10                                     amd64        Display server for Ubuntu - server library
ii  libmirserver47:amd64                            1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - server library
ii  mir-client-platform-mesa5:amd64                 1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - client platform library for Mesa
ii  mir-demos                                       1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - demonstration programs
ii  mir-graphics-drivers-desktop:amd64              1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - desktop driver metapackage
ii  mir-platform-graphics-mesa-kms13:amd64          0.31.2-0ubuntu17.10                                     amd64        Display server for Ubuntu - platform library for KMS Mesa
ii  mir-platform-graphics-mesa-kms15:amd64          1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - platform library for KMS Mesa
ii  mir-platform-graphics-mesa-x13:amd64            0.31.2-0ubuntu17.10                                     amd64        Display server for Ubuntu - platform library for X11 Mesa
ii  mir-platform-graphics-mesa-x15:amd64            1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - platform library for X11 Mesa
ii  mir-platform-input-evdev7:amd64                 1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - input platform library
ii  mir-utils                                       1.0.0+0~20181002215523.10~1.gbpdede9b                   amd64        Display server for Ubuntu - utility programs
ii  qtdeclarative5-qtmir-plugin:amd64               0.5.3+ubports1+0~20180918223824.20~1.gbpb37293          amd64        Qt plugin for Unity specific Mir APIs
ii  qtmir-desktop:amd64                             0.5.3+ubports1+0~20180918223824.20~1.gbpb37293          amd64        Qt platform abstraction (QPA) plugin for a Mir server (desktop)
ii  xmir                                            2:1.19.7+ubports1+0~20180221013947.2~1.gbp98d4ca        amd64        Xmir X server

**Comment by pixelr0** [comment]
ummm... after the last update i can now login, yay (second try)

![screenshot20181004_080806803](https://user-images.githubusercontent.com/333589/46454199-b6815900-c7ad-11e8-92a0-0421d8d926f3.png)

**Comment by dobey** [comment]
So we can close this now? Seems to be on par with behavior when using lightdm at least.

**Comment by pixelr0** [comment]
yep, closed
